### ISSUE TITLE
Way to print just error message

### ISSUE THREAD

**Issue by alecjacobson** [iheartla/iheartla#32]
Is it possible / could I make a feature request to print just the error message and suppress the exception traceback?

For example suppose `test.txt` contains:

```
B = [ A C ]

where

A ℝ ^ (4 × 4): a matrix
C: ℝ ^ (4 × 4): a matrix
E: { ℤ × ℤ }
```

(that is, an error on the `A ℝ ^ (4 × 4): a matrix` line). If I run `python app.py -o eigen test.txt` then I see:

```
  File "app.py", line 30, in <module>
    for input in args.input: compile_la_file(input, parser_type)
  File "/Users/ajx/Repos/iheartla/iheartla/la_parser/parser.py", line 378, in compile_la_file
    model = parser.parse(content, parseinfo=True)
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/tatsu/contexts.py", line 229, in parse
    raise self._furthest_exception
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/tatsu/contexts.py", line 700, in _option
    yield
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/tatsu/contexts.py", line 786, in _repeat
    self._isolate(block)
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/tatsu/contexts.py", line 765, in _isolate
    block()
  File "/Users/ajx/Repos/iheartla/iheartla/la_local_parsers/init_parser.py", line 3451, in block1
    self._hspace_()
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/tatsu/contexts.py", line 56, in wrapper
    return self._call(ruleinfo)
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/tatsu/contexts.py", line 523, in _call
    result = self._recursive_call(ruleinfo)
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/tatsu/contexts.py", line 552, in _recursive_call
    return self._invoke_rule(ruleinfo, self.memokey)
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/tatsu/contexts.py", line 601, in _invoke_rule
    ruleinfo.impl(self)
  File "/Users/ajx/Repos/iheartla/iheartla/la_local_parsers/init_parser.py", line 2288, in _hspace_
    self._error('no available options')
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/tatsu/contexts.py", line 460, in _error
    raise self._make_exception(item, exclass=exclass)
tatsu.exceptions.FailedParse: (5:3) no available options :
A ℝ ^ (4 × 4): a matrix
  ^
hspace
where_condition
where_conditions
params_block
valid_block
start
```

I would like to suppress everything except 

```
A ℝ ^ (4 × 4): a matrix
  ^
```

For a command line app, it might make sense to send this to stderr and have an optional flag for this other debug output.

**Comment by pressureless** [comment]
It should print the same error message as in the GUI now

**Comment by alecjacobson** [comment]
I pulled and now it's displaying:

```
Skipping visualizer.
Traceback (most recent call last):
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/tatsu/contexts.py", line 221, in parse
    result = rule()
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/tatsu/contexts.py", line 56, in wrapper
    return self._call(ruleinfo)
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/tatsu/contexts.py", line 523, in _call
    result = self._recursive_call(ruleinfo)
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/tatsu/contexts.py", line 552, in _recursive_call
    return self._invoke_rule(ruleinfo, self.memokey)
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/tatsu/contexts.py", line 601, in _invoke_rule
    ruleinfo.impl(self)
  File "/Users/ajx/Repos/iheartla/iheartla/la_local_parsers/init_parser.py", line 133, in _start_
    self._check_eof()
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/tatsu/contexts.py", line 670, in _check_eof
    self._error('Expecting end of text', exclass=FailedExpectingEndOfText)
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/tatsu/contexts.py", line 460, in _error
    raise self._make_exception(item, exclass=exclass)
tatsu.exceptions.FailedExpectingEndOfText: (3:1) Expecting end of text :
where
^
start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ajx/Repos/iheartla/iheartla/la_parser/parser.py", line 379, in compile_la_file
    model = parser.parse(content, parseinfo=True)
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/tatsu/contexts.py", line 229, in parse
    raise self._furthest_exception
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/tatsu/contexts.py", line 700, in _option
    yield
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/tatsu/contexts.py", line 786, in _repeat
    self._isolate(block)
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/tatsu/contexts.py", line 765, in _isolate
    block()
  File "/Users/ajx/Repos/iheartla/iheartla/la_local_parsers/init_parser.py", line 3451, in block1
    self._hspace_()
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/tatsu/contexts.py", line 56, in wrapper
    return self._call(ruleinfo)
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/tatsu/contexts.py", line 523, in _call
    result = self._recursive_call(ruleinfo)
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/tatsu/contexts.py", line 552, in _recursive_call
    return self._invoke_rule(ruleinfo, self.memokey)
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/tatsu/contexts.py", line 601, in _invoke_rule
    ruleinfo.impl(self)
  File "/Users/ajx/Repos/iheartla/iheartla/la_local_parsers/init_parser.py", line 2288, in _hspace_
    self._error('no available options')
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/tatsu/contexts.py", line 460, in _error
    raise self._make_exception(item, exclass=exclass)
tatsu.exceptions.FailedParse: (5:3) no available options :
A ℝ ^ (4 × 4): a matrix
  ^
hspace
where_condition
where_conditions
params_block
valid_block
start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 30, in <module>
    for input in args.input: compile_la_file(input, parser_type)
  File "/Users/ajx/Repos/iheartla/iheartla/la_parser/parser.py", line 395, in compile_la_file
    print(LaMsg.getInstance().get_parse_error(e))
  File "/Users/ajx/Repos/iheartla/iheartla/la_tools/la_msg.py", line 128, in get_parse_error
    line_info = err.buf.line_info(err.pos)
AttributeError: 'FailedParse' object has no attribute 'buf'

shell returned 1```

**Comment by alecjacobson** [comment]
ca9875910ee475790d23f1dccdc7fdc9f2ed668c didn't work for me. Now it prints nothing...

**Comment by pressureless** [comment]
Fixed
